package main

import (
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
)

func TestPublishedRepositorySchemaMatchesLoader(t *testing.T) {
	root := repoRoot(t)
	publishedPath := filepath.Join(root, "schema", "repository-declaration.txt")
	published, err := os.ReadFile(publishedPath)
	if err != nil {
		t.Fatal(err)
	}
	want := repositoryDeclarationSchema()
	if string(published) != want {
		t.Fatalf("schema/repository-declaration.txt drifted from the loader schema (%d published bytes, %d generated bytes)", len(published), len(want))
	}

	fields := flattenSchemaFields(repositorySchemaTree())
	notes := repositoryFieldNotes()
	if len(notes) != len(fields) {
		t.Fatalf("schema notes = %d, loader fields = %d", len(notes), len(fields))
	}
	seen := map[string]struct{}{}
	for _, field := range fields {
		if _, dup := seen[field.Path]; dup {
			t.Fatalf("duplicate schema path %s", field.Path)
		}
		seen[field.Path] = struct{}{}
		note, ok := notes[field.Path]
		if !ok || note == "" {
			t.Fatalf("published schema has no note for loader field %s", field.Path)
		}
		needle := "- " + field.Path + ": " + field.TypeName + ", " + field.Presence + "\n"
		if !strings.Contains(string(published), needle) {
			t.Fatalf("published schema missing loader field %q", needle)
		}
	}
	for path := range notes {
		if _, ok := seen[path]; !ok {
			t.Fatalf("schema note %s is not a loader field", path)
		}
	}

	for _, value := range []string{
		repositoryProviderGitHub,
		lifecycleRemoveRetain,
		lifecycleExistingAdopt,
		lifecycleExistingRefuse,
		visibilityPublic,
		visibilityPrivate,
		actionsAllowedAll,
		actionsAllowedLocal,
		actionsAllowedSelected,
	} {
		if !strings.Contains(string(published), value) {
			t.Fatalf("published schema missing allowed value %q", value)
		}
	}
	for _, role := range sortedRoleNames() {
		if !strings.Contains(string(published), role) {
			t.Fatalf("published schema missing role %q", role)
		}
	}
	for _, marker := range secretMaterialMarkers {
		if !strings.Contains(string(published), marker) {
			t.Fatalf("published schema missing rejected secret marker %q", marker)
		}
	}
	for _, limit := range []int{maxDescriptionRunes, maxReviewCount, maxRepositoryFileBytes, maxActionPatternBytes, maxCheckContextRunes, maxActionSegments} {
		if !strings.Contains(string(published), strconv.Itoa(limit)) {
			t.Fatalf("published schema missing limit %d", limit)
		}
	}
	if strings.Contains(string(published), "\n- id:") {
		t.Fatal("schema lists id as a YAML field; the loader takes id from the filename")
	}

	for _, forbidden := range []string{
		"GENESIS_SYNC_TOKEN",
		"/var/lib/genesis/secrets",
		"/var/lib/genesis/credentials",
		"providers.d",
		"PRIVATE KEY",
		"BEGIN PRIVATE",
	} {
		if strings.Contains(string(published), forbidden) {
			t.Fatalf("published schema contains %q", forbidden)
		}
	}
	if !strings.Contains(string(published), "Do not write app_id or installation_id.") || !strings.Contains(string(published), "Company App install is Genesis's job, not the designer's.") {
		t.Fatal("schema does not forbid app_id and installation_id")
	}
	if strings.Contains(string(published), "app_id:") || strings.Contains(string(published), "installation_id:") {
		t.Fatal("schema lists app_id or installation_id as a field")
	}

	example := schemaExample(t, string(published))
	if example != repositorySchemaExample() {
		t.Fatal("published example drifted from repositorySchemaExample")
	}
	dir := t.TempDir()
	writeRepoFile(t, dir, "widget.yaml", example)
	loaded, active, err := loadRepositories(dir)
	if err != nil || !active {
		t.Fatalf("schema example did not load: active=%v err=%v", active, err)
	}
	widget := loaded["widget"]
	if widget.Provider != repositoryProviderGitHub || widget.Lifecycle.Existing != lifecycleExistingAdopt || widget.Settings.Visibility != visibilityPrivate {
		t.Fatalf("schema example = %#v", widget)
	}
	if widget.Actions.Allowed != actionsAllowedSelected || len(widget.Actions.Selected) != 1 || widget.Protection == nil || widget.Secrets == nil || len(widget.Identities) != 2 {
		t.Fatalf("schema example omitted loader sections: %#v", widget)
	}

	dockerfile, err := os.ReadFile(filepath.Join(root, "Dockerfile"))
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(dockerfile), "COPY schema/repository-declaration.txt "+repositorySchemaImagePath) {
		t.Fatalf("Dockerfile does not install the schema at %s", repositorySchemaImagePath)
	}
	if !strings.Contains(string(dockerfile), "chmod -R a+rX") || !strings.Contains(string(dockerfile), "/usr/share/genesis/schema") {
		t.Fatal("Dockerfile does not make /usr/share/genesis/schema world-readable")
	}
	if strings.Contains(repositorySchemaImagePath, "/var/lib/genesis/config") || strings.Contains(repositorySchemaImagePath, "/etc/genesis") {
		t.Fatalf("schema path %s is inside designer config or provider policy", repositorySchemaImagePath)
	}

	agents, err := loadAgents(filepath.Join(root, "agents.d"))
	if err != nil {
		t.Fatal(err)
	}
	designer := agents["designer"]
	for _, phrase := range []string{
		repositorySchemaImagePath,
		"instead of inspecting the genesis binary",
		"Do not run strings, grep, or readelf on the genesis binary",
		"not the contract",
	} {
		if !strings.Contains(designer.Instructions, phrase) {
			t.Fatalf("designer instructions missing %q", phrase)
		}
	}
}

func schemaExample(t *testing.T, schema string) string {
	t.Helper()
	start := strings.Index(schema, repositorySchemaExampleBegin)
	stop := strings.Index(schema, repositorySchemaExampleEnd)
	if start < 0 || stop < 0 || stop < start {
		t.Fatal("published schema is missing the example block")
	}
	return schema[start+len(repositorySchemaExampleBegin) : stop]
}
